name: CakeHomePlugin
main: de.lycake.CakeHomePlugin.CakeHomePlugin
version: 0.42
author: Lycake

commands:
    home:
        description: Set your home an teleport back there
        permission: CakeHomePlugin.home
        usage: |
            /home [set]

permissions:
    CakeHomePlugin.home:
        description: Gives access to CakeHome commands
        default: op
